services:
  my-project:
    build: .
    container_name: my_project_container
    env_file:
      - .env
    environment:
      - DB_USER=${DB_USER}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    ports:
      - "8000:8000"
    volumes:
      - .:/my_project
    depends_on:
      - db
    networks:
      - my_project_network

  db:
    image: postgres:17.5-alpine
    container_name: my_project_db
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - my_project_network

networks:
  my_project_network:
    driver: bridge

volumes:
  db_data:
    driver: local